export const projectsData = [
  {
    id: 'testi-platvorm',
    title: 'Testiplatvorm',
    subtitle: 'Vali IT! Team Project - 4 Developers',
    description: 'A full-stack competence testing platform where managers build tests from a question bank, assign them to users and review auto-graded results. Includes role-based access and AI-generated questions with a human review step.',
    contribution: 'Built the test creation feature end-to-end (Vue form, REST API, database logic). Developed the AI question-generation chat and the question bank with AI-assisted coding.',
    link: 'https://github.com/magicflute21/testi-platvorm',
    tags: [
      'Java 21',
      'Spring Boot',
      'Vue 3',
      'PostgreSQL',
      'RESTful API',
      'Swagger / OpenAPI',
      'Spring AI',
      'Git Team Workflow',
      'Jira / Agile',
    ],
  },
  {
    id: 'reddit-clone',
    title: 'Reddit Clone',
    subtitle: 'Front-End Course Project',
    description: 'A Reddit client for browsing subreddits, searching posts and reading comments, with loading skeleton states. A small Node.js/Express proxy server fetches data from the Reddit JSON API. Runs locally, since Reddit blocks requests from hosted servers.',
    link: 'https://github.com/tiina-re/reddit-client-project',
    tags: [
      'React',
      'Redux Toolkit',
      'React Router',
      'Node.js / Express',
      'Reddit JSON API',
      'Asynchronous JS',
      'Vitest / Testing Library',
      'Git/GitHub',
    ],
  },
  {
    id: 'sonasemu-learning-app',
    title: 'Sõnasemu Learning App',
    subtitle: 'Personal Project - In Progress',
    description: 'An accessible learning application designed to support autistic children with letters, words, and numbers through structured activities and parent or educator dashboard views.',
    tags: [
      'React',
      'TypeScript',
      'Vite',
      'Tailwind CSS',
      'React Context API',
      'Custom Hooks',
      'Accessibility (a11y)',
      'UI/UX for Neurodiversity',
    ],
  },
];
