export const projectsData = [
  {
    id: 'spotify-clone',
    title: 'Spotify Clone',
    subtitle: 'Front-End Course Project',
    description: 'A responsive music streaming web player interface with playlist management, audio playback controls, persistent state, and custom sidebar navigation.',
    tags: [
      'React',
      'HTML5/CSS3',
      'Context API',
      'JavaScript (ES6+)',
      'REST APIs',
      'Audio Web API',
      'Responsive Design',
    ],
  },
  {
    id: 'reddit-clone',
    title: 'Reddit Clone',
    subtitle: 'Front-End Course Project',
    description: 'A client-side Reddit-style application with API integrations, global data fetching, post sorting, subreddit browsing, and loading skeleton states.',
    tags: [
      'React',
      'Node.js',
      'Express',
      'MongoDB',
      'JSON REST API',
      'Asynchronous JS',
      'Loading Skeletons',
      'Git/GitHub',
    ],
  },
  {
    id: 'sonasemu-learning-app',
    title: 'Sõnasemu Learning App',
    subtitle: 'Personal Project - In Progress',
    description: 'An accessible learning application designed to support autistic children with letters, words, and numbers through structured activities and parent or educator dashboard views.',
    tags: [
      'React',
      'TypeScript',
      'Vite',
      'Tailwind CSS',
      'React Context API',
      'Custom Hooks',
      'Accessibility (a11y)',
      'UI/UX for Neurodiversity',
    ],
  },
];
